title: Klave Network documentation
description: Developer documentation for Klave Network
theme: just-the-docs

url: https://klave.network/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

remote_theme: just-the-docs/just-the-docs@v0.4.0

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  GitHub: https://github.com/klave-network
